# Generated by Django 6.0.6 on 2026-06-19 20:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('COLLECTION', 'Collection'), ('SALE', 'Sale'), ('ADJUSTMENT_ADD', 'Adjustment Add'), ('ADJUSTMENT_SUBTRACT', 'Adjustment Subtract')], max_length=20)),
                ('milk_type', models.CharField(choices=[('COW', 'Cow'), ('BUFFALO', 'Buffalo')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('milk_type', models.CharField(choices=[('COW', 'Cow'), ('BUFFALO', 'Buffalo')], max_length=10)),
                ('adjustment_type', models.CharField(choices=[('ADD', 'Add'), ('SUBTRACT', 'Subtract')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('SPOILAGE', 'Spoilage'), ('LEAKAGE', 'Leakage'), ('TESTING', 'Testing'), ('PERSONAL_USE', 'Personal Use'), ('DONATION', 'Donation'), ('MANUAL_CORRECTION', 'Manual Correction'), ('OTHER', 'Other')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_adjustments',
                'ordering': ['-created_at'],
            },
        ),
    ]
