version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: kisangat_db
    environment:
      MYSQL_DATABASE: kisangat
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: kisangat_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=db

  frontend:
    build: ./frontend
    container_name: kisangat_frontend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api

volumes:
  mysql_data:
