# Generated by Django 6.0.6 on 2026-06-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkcollection',
            name='shift',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening')], default='MORNING', max_length=10),
        ),
        migrations.AddField(
            model_name='milkcollection',
            name='snf_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
