# Generated by Django 6.0.6 on 2026-06-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
    ]
