# Generated by Django 6.0.6 on 2026-06-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milksale',
            name='shift',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening')], default='MORNING', max_length=10),
        ),
    ]
