# Generated by Django 6.0.6 on 2026-06-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_milksale_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='milksale',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('DUE', 'Due')], default='DUE', max_length=10),
        ),
        migrations.AddField(
            model_name='milksale',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
